"""The no-session-link guard, checked against real and synthetic commit messages.

The pattern is the one actually observed in practice (see the change's
proposal.md and design.md): a `Claude-Session:` trailer, or a
`_Generated by [Claude Code](https://claude.ai/code/session_...)_` footer --
both contain the same substring, `claude.ai/code/session`.
"""

import pytest

from scripts.check_no_session_link import check, main


@pytest.mark.spec("foundation/a-commit-message-containing-a-coding-session-link-is-refused")
def test_a_claude_session_trailer_is_reported():
    message = (
        "Fix the thing\n\n"
        "Co-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>\n"
        "Claude-Session: https://claude.ai/code/session_01ABC\n"
    )

    assert check(message) == ["Claude-Session: https://claude.ai/code/session_01ABC"]


def test_a_footer_style_link_is_reported():
    message = (
        "Fix the thing\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_01XYZ)_\n"
    )

    assert len(check(message)) == 1


def test_case_insensitive_match():
    assert check("See HTTPS://CLAUDE.AI/CODE/SESSION_XYZ") != []


def test_a_clean_commit_message_passes():
    message = "Fix the thing\n\nCo-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>\n"

    assert check(message) == []


def test_an_unrelated_url_does_not_match():
    message = "See https://github.com/Graftwork/stock/pull/13 for context.\n"

    assert check(message) == []


@pytest.mark.spec("foundation/a-commit-message-containing-a-coding-session-link-is-refused")
def test_main_refuses_a_message_with_a_link_and_names_the_line(tmp_path, capsys):
    message_file = tmp_path / "COMMIT_EDITMSG"
    message_file.write_text(
        "Fix the thing\n\nClaude-Session: https://claude.ai/code/session_01ABC\n",
        encoding="utf-8",
    )

    assert main([str(message_file)]) == 1

    stderr = capsys.readouterr().err
    assert "Claude-Session: https://claude.ai/code/session_01ABC" in stderr


def test_main_accepts_a_clean_message(tmp_path, capsys):
    message_file = tmp_path / "COMMIT_EDITMSG"
    message_file.write_text(
        "Fix the thing\n\nCo-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>\n",
        encoding="utf-8",
    )

    assert main([str(message_file)]) == 0
    assert capsys.readouterr().err == ""


def test_main_without_a_path_is_a_usage_error(capsys):
    assert main([]) == 2
    assert "expected the commit message file path" in capsys.readouterr().err
